services:
  - type: web
    name: seto-ai-compiler
    env: python
    buildCommand: "npm install && npm run build && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: FLASK_ENV
        value: production
